[WIP] LASTDATA POSTGRES SINK deadlock problem
telefonicaid/fiware-cygnus pull request #2199
Opened 2022-10-07 10:01 UTC by fgalan

Issue #2197 

This is a first approach to the solution.

Using primary keys in conf this way

```
cygnus-ngsi.sinks.postgis-sink-lastdata.last_data_unique_key = entityid,foo,bar
```

Using this script (two notifications, first BOMBA-002 with the three keys, second with BOMBA-001 without the keys):

```
CYGNUS_5057="http://localhost:5056/notify"

echo "Notifying..."
curl $CYGNUS_5057 -v -H 'fiware-service: urbodeployer' -H 'fiware-servicepath: /palenciacicloagua' -H 'ngsiv2-attrsformat: normalized' -H 'content-type: application/json; charset=utf-8' -d @- <<EOF
{"subscriptionId":"63355d4ccdc089718a5603d4","data":[{"id":"BOMBA-SS2","type":"WaterPump","TimeInstant":{"type":"DateTime","value":"2022-09-29T09:20:00.030Z","metadata":{}},"entityid": {"value": "A", "type": "Text", "metadata":{}}, "foo": {"value": "B", "type": "Text","metadata":{}}, "bar": {"value": "C", "type": "Text", "metadata":{}}, "battery":{"type":"Number","value":0.781376938,"metadata":{}},"batteryMinThreshold":{"type":"Number","value":0.270906825,"metadata":{}},"batteryMaxThreshold":{"type":"Number","value":1,"metadata":{}},"probingFlowMeter":{"type":"Number","value":0,"metadata":{}},"pumpStatus":{"type":"Number","value":0,"metadata":{}},"wellFlowMeter":{"type":"Number","value":0,"metadata":{}}}]}
EOF

echo "Notifying..."
curl $CYGNUS_5057 -v -H 'fiware-service: jcyl' -H 'fiware-servicepath: /ciclodelagua' -H 'ngsiv2-attrsformat: normalized' -H 'content-type: application/json; charset=utf-8' -d @- <<EOF
{"subscriptionId":"63355d4ccdc089718a5603d4","data":[{"id":"BOMBA-SS1","type":"WaterPump","TimeInstant":{"type":"DateTime","value":"2022-09-29T09:20:00.030Z","metadata":{}},"battery":{"type":"Number","value":0.781376938,"metadata":{}},"batteryMinThreshold":{"type":"Number","value":0.270906825,"metadata":{}},"batteryMaxThreshold":{"type":"Number","value":1,"metadata":{}},"probingFlowMeter":{"type":"Number","value":0,"metadata":{}},"pumpStatus":{"type":"Number","value":0,"metadata":{}},"wellFlowMeter":{"type":"Number","value":0,"metadata":{}}}]}
EOF
```

We get this in log (error is due to table doesn't exist, but no SQL syntax error happends, so they are correct):

```
22/10/07 09:25:56 ERROR sinks.NGSISink: BadContextData ( SQLException). POSTGRESQL null Data insertion error. database: jcyl upsertQuerys:  currentUpsertQuery: INSERT INTO jcyl.ciclodelagua_waterpump_lastdata (entityid,bar,foo,entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES (null, null, null,'BOMBA-SS1','WaterPump','/ciclodelagua','2022-10-07 09:25:54.411',0,0.270906825,0,0.781376938,'2022-09-29T09:20:00.030Z',0,1) ON CONFLICT (entityid,bar,foo) DO UPDATE SET entityId=EXCLUDED.entityId, entityType=EXCLUDED.entityType, fiwareServicePath=EXCLUDED.fiwareServicePath, recvTime=EXCLUDED.recvTime, probingFlowMeter=EXCLUDED.probingFlowMeter, batteryMinThreshold=EXCLUDED.batteryMinThreshold, wellFlowMeter=EXCLUDED.wellFlowMeter, battery=EXCLUDED.battery, TimeInstant=EXCLUDED.TimeInstant, pumpStatus=EXCLUDED.pumpStatus, batteryMaxThreshold=EXCLUDED.batteryMaxThreshold WHERE jcyl.ciclodelagua_waterpump_lastdata.entityid=EXCLUDED.entityid AND jcyl.ciclodelagua_waterpump_lastdata.bar=EXCLUDED.bar AND jcyl.ciclodelagua_waterpump_lastdata.foo=EXCLUDED.foo AND to_timestamp(jcyl.ciclodelagua_waterpump_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') (ERROR: relation "jcyl.ciclodelagua_waterpump_lastdata" does not exist
  Position: 13).  Sink: postgis-type-database-sink-lastdata Destination: jcyl_/ciclodelagua_WaterPump Stack trace: 

22/10/07 09:25:57 ERROR sinks.NGSISink: BadContextData ( SQLException). POSTGRESQL null Data insertion error. database: urbodeployer upsertQuerys:  currentUpsertQuery: INSERT INTO urbodeployer.palenciacicloagua_waterpump_lastdata (entityid,bar,foo,entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES ('A','C','B','BOMBA-SS2','WaterPump','/palenciacicloagua','2022-10-07 09:25:54.300',0,0.270906825,0,0.781376938,'2022-09-29T09:20:00.030Z',0,1) ON CONFLICT (entityid,bar,foo) DO UPDATE SET entityId=EXCLUDED.entityId, entityType=EXCLUDED.entityType, fiwareServicePath=EXCLUDED.fiwareServicePath, recvTime=EXCLUDED.recvTime, probingFlowMeter=EXCLUDED.probingFlowMeter, batteryMinThreshold=EXCLUDED.batteryMinThreshold, wellFlowMeter=EXCLUDED.wellFlowMeter, battery=EXCLUDED.battery, TimeInstant=EXCLUDED.TimeInstant, pumpStatus=EXCLUDED.pumpStatus, batteryMaxThreshold=EXCLUDED.batteryMaxThreshold WHERE urbodeployer.palenciacicloagua_waterpump_lastdata.entityid=EXCLUDED.entityid AND urbodeployer.palenciacicloagua_waterpump_lastdata.bar=EXCLUDED.bar AND urbodeployer.palenciacicloagua_waterpump_lastdata.foo=EXCLUDED.foo AND to_timestamp(urbodeployer.palenciacicloagua_waterpump_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') (ERROR: relation "urbodeployer.palenciacicloagua_waterpump_lastdata" does not exist
  Position: 13).  Sink: postgis-type-database-sink-lastdata Destination: urbodeployer_/palenciacicloagua_WaterPump Stack trace: 
```

Note the reordering seems to work fine within the batch: first BOMBA-001 query, next BOMBA-002 (although notifications are in different order)

2022-10-10 16:55 UTC, fgalan commented on cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/aggregation/NGSIGenericColumnAggregator.java
>                                      get(i).getAsString());
Not sure if the guards for not null in this file are actually needed... While I was working on unit tests I got some null pointer exceptions but I'm not sure if they can raise in real usage conditions.

Anyway, I think it doesn't hurt, as extra security measure in the code.

2022-10-13 14:52 UTC, fgalan commented on doc/cygnus-ngsi/flume_extensions_catalogue/last_data_function.md
> +(entityId,entityType,fiwareServicePath,recvTime,fillingLevel,fillingLevel_md)
We haven't tested anything on the MySQL sink. I think the aggregation will be also affect it (due to the needed changes in NGSIMySQLSinkTest.java to keep tests passing) but not fully sure.

2022-10-13 15:41 UTC, fgalan commented
At commit [4815de8](https://github.com/telefonicaid/fiware-cygnus/pull/2199/commits/4815de8a70748c95ac834ff3a74e3744d8840b77):

```
22/10/13 15:36:50 ERROR sinks.NGSISink: BadContextData ( SQLException). POSTGRESQL null Data insertion error. database: jcyl upsertQuerys:  currentUpsertQuery: INSERT INTO jcyl.ciclodelagua_waterpump_lastdata (entityid,bar,foo,entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES (null,null,null,'BOMBA-SS1','WaterPump','/ciclodelagua','2022-10-13 15:36:43.802',0,0.270906825,0,0.781376938,'2022-09-29T09:20:00.030Z',0,1) ON CONFLICT (entityid,bar,foo) DO UPDATE SET entityId=EXCLUDED.entityId,entityType=EXCLUDED.entityType,fiwareServicePath=EXCLUDED.fiwareServicePath,recvTime=EXCLUDED.recvTime,probingFlowMeter=EXCLUDED.probingFlowMeter,batteryMinThreshold=EXCLUDED.batteryMinThreshold,wellFlowMeter=EXCLUDED.wellFlowMeter,battery=EXCLUDED.battery,TimeInstant=EXCLUDED.TimeInstant,pumpStatus=EXCLUDED.pumpStatus,batteryMaxThreshold=EXCLUDED.batteryMaxThreshold WHERE jcyl.ciclodelagua_waterpump_lastdata.entityid=EXCLUDED.entityid AND jcyl.ciclodelagua_waterpump_lastdata.bar=EXCLUDED.bar AND jcyl.ciclodelagua_waterpump_lastdata.foo=EXCLUDED.foo AND to_timestamp(jcyl.ciclodelagua_waterpump_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') (ERROR: relation "jcyl.ciclodelagua_waterpump_lastdata" does not exist
  Position: 13).  Sink: postgis-type-database-sink-lastdata Destination: jcyl_/ciclodelagua_WaterPump Stack trace: 
22/10/13 15:36:51 ERROR sinks.NGSISink: BadContextData ( SQLException). POSTGRESQL null Data insertion error. database: urbodeployer upsertQuerys:  currentUpsertQuery: INSERT INTO urbodeployer.palenciacicloagua_waterpump_lastdata (entityid,bar,foo,entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES ('A','C','B','BOMBA-SS2','WaterPump','/palenciacicloagua','2022-10-13 15:36:43.244',0,0.270906825,0,0.781376938,'2022-09-29T09:20:00.030Z',0,1) ON CONFLICT (entityid,bar,foo) DO UPDATE SET entityId=EXCLUDED.entityId,entityType=EXCLUDED.entityType,fiwareServicePath=EXCLUDED.fiwareServicePath,recvTime=EXCLUDED.recvTime,probingFlowMeter=EXCLUDED.probingFlowMeter,batteryMinThreshold=EXCLUDED.batteryMinThreshold,wellFlowMeter=EXCLUDED.wellFlowMeter,battery=EXCLUDED.battery,TimeInstant=EXCLUDED.TimeInstant,pumpStatus=EXCLUDED.pumpStatus,batteryMaxThreshold=EXCLUDED.batteryMaxThreshold WHERE urbodeployer.palenciacicloagua_waterpump_lastdata.entityid=EXCLUDED.entityid AND urbodeployer.palenciacicloagua_waterpump_lastdata.bar=EXCLUDED.bar AND urbodeployer.palenciacicloagua_waterpump_lastdata.foo=EXCLUDED.foo AND to_timestamp(urbodeployer.palenciacicloagua_waterpump_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') (ERROR: relation "urbodeployer.palenciacicloagua_waterpump_lastdata" does not exist
  Position: 13).  Sink: postgis-type-database-sink-lastdata Destination: urbodeployer_/palenciacicloagua_WaterPump Stack trace: 
```

Which seems to be the same we got at first commit, so regression is ok.

2022-10-13 16:10 UTC, fgalan commented on doc/cygnus-ngsi/flume_extensions_catalogue/last_data_function.md
>  AND to_timestamp(pruebapostmanx.subpruebapostman_5dde9_wastecontainer_last_data.recvTime, 'YYYY-MM-DD HH24:MI:SS.MS')
This documentation has been checked using this conf:

```
cygnus-ngsi.sinks.postgis-type-database-sink-lastdata.last_data_unique_key = entityId
```

And getting this from traces:

```
INSERT INTO urbodeployer.palenciacicloagua_waterpump_lastdata
(entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,entityid,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES (....)
ON CONFLICT (entityId) DO UPDATE SET
entityType=EXCLUDED.entityType,fiwareServicePath=EXCLUDED.fiwareServicePath,recvTime=EXCLUDED.recvTime,
probingFlowMeter=EXCLUDED.probingFlowMeter,batteryMinThreshold=EXCLUDED.batteryMinThreshold,wellFlowMeter=EXCLUDED.wellFlowMeter,entityid=EXCLUDED.entityid,battery=EXCLUDED.battery,TimeInstant=EXCLUDED.TimeInstant,pumpStatus=EXCLUDED.pumpStatus,batteryMaxThreshold=EXCLUDED.batteryMaxThreshold
WHERE urbodeployer.palenciacicloagua_waterpump_lastdata.entityId=EXCLUDED.entityId
AND to_timestamp(urbodeployer.palenciacicloagua_waterpump_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS')
```

2022-10-13 16:12 UTC, fgalan commented on doc/cygnus-ngsi/flume_extensions_catalogue/last_data_function.md
>  AND to_timestamp(pruebapostmanx.subpruebapostman_5dde9_wastecontainer_last_data.recvTime, 'YYYY-MM-DD HH24:MI:SS.MS')
A slight different in the last line has been fixed in this commit cf485d8804688851eb70cee4f881cbae60043e74

2022-10-14 07:45 UTC, fgalan commented
It has failed in LAB environment (as in commit [d8b811a](https://github.com/telefonicaid/fiware-cygnus/pull/2199/commits/d8b811a43f846503fe16643fc9070a86d802c5a9))

```
time=2022-10-14T07:30:39.739Z | lvl=ERROR | corr=ed8d68c1-ae79-4ffb-9ddc-b0fdf9b20957; cbnotif=2 | trans=dca4ce7b-db61-458a-8885-2185a73054a8 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[604] : BadContextData ( SQLException). POSTGRESQL null Data insertion error. database: urbo2 upsertQuerys:  currentUpsertQuery: INSERT INTO alcobendas.parking_parkingaccess_lastdata (entityid,entityId,entityType,fiwareServicePath,recvTime,alertStatus,vehicleEntranceCount,accessModified,accessWay,vehicleExitCount,refOffStreetParking,name,description,location,alertText,TimeInstant) VALUES (null,'ParkingAccess:18AB1EBO4','ParkingAccess','/parking','2022-10-14 07:30:33.28','ok',6,'2022-10-14T07:30:33.001Z','entrance',3,'OffStreetParking:BO4','18 AB LINEA 1 E BO4','[PDTE]',ST_GeomFromGeoJSON('{"type":"Point","coordinates":[-6.007751226,37.410706955]}'),'ok','2022-10-14T07:30:33.001Z') ON CONFLICT (entityid) DO UPDATE SET entityId=EXCLUDED.entityId,entityType=EXCLUDED.entityType,fiwareServicePath=EXCLUDED.fiwareServicePath,recvTime=EXCLUDED.recvTime,alertStatus=EXCLUDED.alertStatus,vehicleEntranceCount=EXCLUDED.vehicleEntranceCount,accessModified=EXCLUDED.accessModified,accessWay=EXCLUDED.accessWay,vehicleExitCount=EXCLUDED.vehicleExitCount,refOffStreetParking=EXCLUDED.refOffStreetParking,name=EXCLUDED.name,description=EXCLUDED.description,location=EXCLUDED.location,alertText=EXCLUDED.alertText,TimeInstant=EXCLUDED.TimeInstant WHERE alcobendas.parking_parkingaccess_lastdata.entityid=EXCLUDED.entityid AND to_timestamp(alcobendas.parking_parkingaccess_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') (ERROR: column "entityid" specified more than once
```

2022-10-14 13:52 UTC, mapedraza commented
Testing :nodeadlock docker image, I got the following results regarding datamodels
| datamodel|database|schema|table|
| ---------|--------|------|-----|
| dm-by-fixed-entity-type-database-schema | service | _servicepath | entitytype |
| dm-by-fixed-entity-type-database	    | service | service | entitytype |
| dm-by-fixed-entity-type	                | agent.conf | service | entitytype |
| dm-by-entity-database-schema	        | service | _servicepath  | servicepath_entityname_entitytype |
| dm-by-attribute                         | agent.conf | service | servicepath_entityname_entitytype_attribute  |
| dm-by-entity-type-database-schema       | service | _servicepath | servicepath_entitytype |
| dm-by-entity-type-database              | service | service | servicepath_entitytype |
| dm-by-entity-database	                | service | service | servicepath_entityname_entitytype |
| dm-by-entity-type	                    | agent.conf | service | servicepath_entitytype  |
| dm-by-service-path	                    | agent.conf | service | servicepath |
| dm-by-entity                            | agent.conf | service | servicepath_entityname_entitytype  |

2022-10-17 17:25 UTC, mrutid requested changes
remove unnecessary "if" expression

2022-10-18 06:50 UTC, fgalan commented
Nest test in 

With 

```
cygnus-ngsi.sinks.postgis-type-database-sink-lastdata.last_data_unique_key = entityid,bar,foo
```

Notifying:

```
CYGNUS_5057="http://localhost:5056/notify"

echo "Notifying (with foo and bar)..."
curl $CYGNUS_5057 -v -H 'fiware-service: urbodeployer' -H 'fiware-servicepath: /palenciacicloagua' -H 'ngsiv2-attrsformat: normalized' -H 'content-type: application/json; charset=utf-8' -d @- <<EOF
{"subscriptionId":"63355d4ccdc089718a5603d4","data":[{"id":"BOMBA-SS2","type":"WaterPump","TimeInstant":{"type":"DateTime","value":"2022-09-29T09:20:00.030Z","metadata":{}},"foo": {"value": "B", "type": "Text","metadata":{}}, "bar": {"value": "C", "type": "Text", "metadata":{}}, "battery":{"type":"Number","value":0.781376938,"metadata":{}},"batteryMinThreshold":{"type":"Number","value":0.270906825,"metadata":{}},"batteryMaxThreshold":{"type":"Number","value":1,"metadata":{}},"probingFlowMeter":{"type":"Number","value":0,"metadata":{}},"pumpStatus":{"type":"Number","value":0,"metadata":{}},"wellFlowMeter":{"type":"Number","value":0,"metadata":{}}}]}
EOF

echo "Notifying (without foo and bar)..."
curl $CYGNUS_5057 -v -H 'fiware-service: jcyl' -H 'fiware-servicepath: /ciclodelagua' -H 'ngsiv2-attrsformat: normalized' -H 'content-type: application/json; charset=utf-8' -d @- <<EOF
{"subscriptionId":"63355d4ccdc089718a5603d4","data":[{"id":"BOMBA-SS1","type":"WaterPump","TimeInstant":{"type":"DateTime","value":"2022-09-29T09:20:00.030Z","metadata":{}},"battery":{"type":"Number","value":0.781376938,"metadata":{}},"batteryMinThreshold":{"type":"Number","value":0.270906825,"metadata":{}},"batteryMaxThreshold":{"type":"Number","value":1,"metadata":{}},"probingFlowMeter":{"type":"Number","value":0,"metadata":{}},"pumpStatus":{"type":"Number","value":0,"metadata":{}},"wellFlowMeter":{"type":"Number","value":0,"metadata":{}}}]}
EOF
```

Result in logs:

```
22/10/18 06:47:02 ERROR sinks.NGSISink: BadContextData ( SQLException). POSTGRESQL null Data insertion error. database: urbodeployer upsertQuerys:  currentUpsertQuery: INSERT INTO urbodeployer.palenciacicloagua_waterpump_lastdata (bar,foo,entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES ('C','B','BOMBA-SS2','WaterPump','/palenciacicloagua','2022-10-18 06:47:00.103',0,0.270906825,0,0.781376938,'2022-09-29T09:20:00.030Z',0,1) ON CONFLICT (entityid,bar,foo) DO UPDATE SET entityId=EXCLUDED.entityId,entityType=EXCLUDED.entityType,fiwareServicePath=EXCLUDED.fiwareServicePath,recvTime=EXCLUDED.recvTime,probingFlowMeter=EXCLUDED.probingFlowMeter,batteryMinThreshold=EXCLUDED.batteryMinThreshold,wellFlowMeter=EXCLUDED.wellFlowMeter,battery=EXCLUDED.battery,TimeInstant=EXCLUDED.TimeInstant,pumpStatus=EXCLUDED.pumpStatus,batteryMaxThreshold=EXCLUDED.batteryMaxThreshold WHERE urbodeployer.palenciacicloagua_waterpump_lastdata.entityid=EXCLUDED.entityid AND urbodeployer.palenciacicloagua_waterpump_lastdata.bar=EXCLUDED.bar AND urbodeployer.palenciacicloagua_waterpump_lastdata.foo=EXCLUDED.foo AND to_timestamp(urbodeployer.palenciacicloagua_waterpump_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') (ERROR: relation "urbodeployer.palenciacicloagua_waterpump_lastdata" does not exist
  Position: 13).  Sink: postgis-type-database-sink-lastdata Destination: urbodeployer_/palenciacicloagua_WaterPump Stack trace: 

22/10/18 06:47:05 ERROR sinks.NGSISink: BadContextData ( SQLException). POSTGRESQL null Data insertion error. database: jcyl upsertQuerys:  currentUpsertQuery: INSERT INTO jcyl.ciclodelagua_waterpump_lastdata (bar,foo,entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES (null,null,'BOMBA-SS1','WaterPump','/ciclodelagua','2022-10-18 06:47:00.240',0,0.270906825,0,0.781376938,'2022-09-29T09:20:00.030Z',0,1) ON CONFLICT (entityid,bar,foo) DO UPDATE SET entityId=EXCLUDED.entityId,entityType=EXCLUDED.entityType,fiwareServicePath=EXCLUDED.fiwareServicePath,recvTime=EXCLUDED.recvTime,probingFlowMeter=EXCLUDED.probingFlowMeter,batteryMinThreshold=EXCLUDED.batteryMinThreshold,wellFlowMeter=EXCLUDED.wellFlowMeter,battery=EXCLUDED.battery,TimeInstant=EXCLUDED.TimeInstant,pumpStatus=EXCLUDED.pumpStatus,batteryMaxThreshold=EXCLUDED.batteryMaxThreshold WHERE jcyl.ciclodelagua_waterpump_lastdata.entityid=EXCLUDED.entityid AND jcyl.ciclodelagua_waterpump_lastdata.bar=EXCLUDED.bar AND jcyl.ciclodelagua_waterpump_lastdata.foo=EXCLUDED.foo AND to_timestamp(jcyl.ciclodelagua_waterpump_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') (ERROR: relation "jcyl.ciclodelagua_waterpump_lastdata" does not exist
  Position: 13).  Sink: postgis-type-database-sink-lastdata Destination: jcyl_/ciclodelagua_WaterPump Stack trace: 
```

Note in this case BOMBA-002 comes before BOMBA-001 but it is a normal consequence on the "unbalanced" notifications given that 

```
INSERT INTO urbodeployer.palenciacicloagua_waterpump_lastdata (bar,foo,entityId,entityType,fiwareServicePath...) VALUES ('C','B','BOMBA-SS2',...
```

comes before than

```
INSERT INTO jcyl.ciclodelagua_waterpump_lastdata (bar,foo,entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES (null,null,'BOMBA-SS1'
```

because `'C'` < 'null'

2022-10-18 07:06 UTC, fgalan commented
New test in d8b811a

Now with this configuration

```
cygnus-ngsi.sinks.postgis-type-database-sink-lastdata.last_data_unique_key = entityId
```

Notifying with "balanced" notifications:

```
CYGNUS_5057="http://localhost:5056/notify"

echo "Notifying..."
curl $CYGNUS_5057 -v -H 'fiware-service: urbodeployer' -H 'fiware-servicepath: /palenciacicloagua' -H 'ngsiv2-attrsformat: normalized' -H 'content-type: application/json; charset=utf-8' -d @- <<EOF
{"subscriptionId":"63355d4ccdc089718a5603d4","data":[{"id":"BOMBA-SS2","type":"WaterPump","TimeInstant":{"type":"DateTime","value":"2022-09-29T09:20:00.030Z","metadata":{}},"battery":{"type":"Number","value":0.781376938,"metadata":{}},"batteryMinThreshold":{"type":"Number","value":0.270906825,"metadata":{}},"batteryMaxThreshold":{"type":"Number","value":1,"metadata":{}},"probingFlowMeter":{"type":"Number","value":0,"metadata":{}},"pumpStatus":{"type":"Number","value":0,"metadata":{}},"wellFlowMeter":{"type":"Number","value":0,"metadata":{}}}]}
EOF

echo "Notifying..."
curl $CYGNUS_5057 -v -H 'fiware-service: jcyl' -H 'fiware-servicepath: /ciclodelagua' -H 'ngsiv2-attrsformat: normalized' -H 'content-type: application/json; charset=utf-8' -d @- <<EOF
{"subscriptionId":"63355d4ccdc089718a5603d4","data":[{"id":"BOMBA-SS1","type":"WaterPump","TimeInstant":{"type":"DateTime","value":"2022-09-29T09:20:00.030Z","metadata":{}},"battery":{"type":"Number","value":0.781376938,"metadata":{}},"batteryMinThreshold":{"type":"Number","value":0.270906825,"metadata":{}},"batteryMaxThreshold":{"type":"Number","value":1,"metadata":{}},"probingFlowMeter":{"type":"Number","value":0,"metadata":{}},"pumpStatus":{"type":"Number","value":0,"metadata":{}},"wellFlowMeter":{"type":"Number","value":0,"metadata":{}}}]}
EOF
```

Result in logs:

```
22/10/18 07:04:21 ERROR sinks.NGSISink: BadContextData ( SQLException). POSTGRESQL null Data insertion error. database: jcyl upsertQuerys:  currentUpsertQuery: INSERT INTO jcyl.ciclodelagua_waterpump_lastdata (entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES ('BOMBA-SS1','WaterPump','/ciclodelagua','2022-10-18 07:04:15.204',0,0.270906825,0,0.781376938,'2022-09-29T09:20:00.030Z',0,1) ON CONFLICT (entityId) DO UPDATE SET entityType=EXCLUDED.entityType,fiwareServicePath=EXCLUDED.fiwareServicePath,recvTime=EXCLUDED.recvTime,probingFlowMeter=EXCLUDED.probingFlowMeter,batteryMinThreshold=EXCLUDED.batteryMinThreshold,wellFlowMeter=EXCLUDED.wellFlowMeter,battery=EXCLUDED.battery,TimeInstant=EXCLUDED.TimeInstant,pumpStatus=EXCLUDED.pumpStatus,batteryMaxThreshold=EXCLUDED.batteryMaxThreshold WHERE jcyl.ciclodelagua_waterpump_lastdata.entityId=EXCLUDED.entityId AND to_timestamp(jcyl.ciclodelagua_waterpump_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') (ERROR: relation "jcyl.ciclodelagua_waterpump_lastdata" does not exist
  Position: 13).  Sink: postgis-type-database-sink-lastdata Destination: jcyl_/ciclodelagua_WaterPump Stack trace: 

22/10/18 07:04:22 ERROR sinks.NGSISink: BadContextData ( SQLException). POSTGRESQL null Data insertion error. database: urbodeployer upsertQuerys:  currentUpsertQuery: INSERT INTO urbodeployer.palenciacicloagua_waterpump_lastdata (entityId,entityType,fiwareServicePath,recvTime,probingFlowMeter,batteryMinThreshold,wellFlowMeter,battery,TimeInstant,pumpStatus,batteryMaxThreshold) VALUES ('BOMBA-SS2','WaterPump','/palenciacicloagua','2022-10-18 07:04:14.727',0,0.270906825,0,0.781376938,'2022-09-29T09:20:00.030Z',0,1) ON CONFLICT (entityId) DO UPDATE SET entityType=EXCLUDED.entityType,fiwareServicePath=EXCLUDED.fiwareServicePath,recvTime=EXCLUDED.recvTime,probingFlowMeter=EXCLUDED.probingFlowMeter,batteryMinThreshold=EXCLUDED.batteryMinThreshold,wellFlowMeter=EXCLUDED.wellFlowMeter,battery=EXCLUDED.battery,TimeInstant=EXCLUDED.TimeInstant,pumpStatus=EXCLUDED.pumpStatus,batteryMaxThreshold=EXCLUDED.batteryMaxThreshold WHERE urbodeployer.palenciacicloagua_waterpump_lastdata.entityId=EXCLUDED.entityId AND to_timestamp(urbodeployer.palenciacicloagua_waterpump_lastdata.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') < to_timestamp(EXCLUDED.recvtime::text, 'YYYY-MM-DD HH24:MI:SS.MS') (ERROR: relation "urbodeployer.palenciacicloagua_waterpump_lastdata" does not exist
  Position: 13).  Sink: postgis-type-database-sink-lastdata Destination: urbodeployer_/palenciacicloagua_WaterPump Stack trace: 
```

Note in this case BOMBA-001 comes before BOMBA-002 in the logs.

2022-10-18 07:09 UTC, fgalan commented
In LAB it seems [ada3feb](https://github.com/telefonicaid/fiware-cygnus/pull/2199/commits/ada3feb6c738032b39cf5609ff669b0417ab206d) is also working well (according to @danielvillalbamota )

2022-10-18 07:10 UTC, fgalan commented on cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/aggregation/NGSIGenericColumnAggregator.java
> +
Fixed in [066c846](https://github.com/telefonicaid/fiware-cygnus/pull/2199/commits/066c8462b48deda44c197d333525ea06cffa9287)

2022-10-18 07:17 UTC, fgalan commented on doc/cygnus-ngsi/flume_extensions_catalogue/last_data_function.md
> +(entityId,entityType,fiwareServicePath,recvTime,fillingLevel,fillingLevel_md)
NTC (informative)

2022-10-18 07:17 UTC, fgalan commented on cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/aggregation/NGSIGenericColumnAggregator.java
>                                      get(i).getAsString());
NTC (informative)

2022-10-18 11:23 UTC, mapedraza commented
LGTM

2022-10-18 12:10 UTC, mrutid approved these changes
Lgtm

2022-10-18 12:11 UTC, merged